import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { hasCompleteEmailDocumentStructure } from "../src/emailUtils.js";

const template = readFileSync(new URL("../src/templates/student-union-announcement.html", import.meta.url), "utf8");
const emailUtilsSource = readFileSync(new URL("../src/emailUtils.js", import.meta.url), "utf8");

test("the production email template has a complete balanced document structure", () => {
  assert.equal(hasCompleteEmailDocumentStructure(template), true);
});

test("the protected email header uses the text-only department identity", () => {
  const header = template.match(/<tr data-protected-section="brand-header">[\s\S]*?<\/tr>\s*<tr>/)?.[0] || "";
  assert.match(header, /class="department-label"/);
  assert.match(header, /class="department-name">Department of Chemistry<\/span><br><span class="representative-name"[^>]*>Student Representatives<\/span>/);
  assert.doesNotMatch(header, /<img\b/i);
  assert.doesNotMatch(template, /assets\.manchester\.ac\.uk\/logos/);
  assert.match(emailUtilsSource, /Department identity and message details/);
  assert.match(emailUtilsSource, /\.department-label \.department-name/);
  assert.match(emailUtilsSource, /\.department-label \.representative-name/);
});

test("the template and newly added components use the compact 12-pixel body scale", () => {
  assert.match(template, /class="mobile-pad email-body-content"[^>]*font-size:12px; line-height:20px;/);
  assert.match(template, /class="fact-value"[^>]*font-size:12px; line-height:19px;/);
  assert.match(template, /class="key-point-row"[\s\S]*?font-size:12px; line-height:20px;/);
  assert.match(template, /class="headline"[^>]*font-size:26px; line-height:34px;/);
  assert.doesNotMatch(template, /font-size:(?:14|15|17|18|28|34)px/);
  assert.match(emailUtilsSource, /data-content-block-type="paragraph"[\s\S]*?font-size:12px; line-height:20px;/);
  assert.doesNotMatch(emailUtilsSource, /font-size:(?:14|15|20)px/);
});

test("the mail-system credit is a protected final row outside the purple footer", () => {
  const credit = 'This mail is generated by Student Representative Mail System';
  assert.equal((template.match(new RegExp(credit, "g")) || []).length, 1);
  assert.match(template, /data-protected-section="system-credit"/);
  assert.match(template, /data-protected-section="system-credit"[^>]*><td[^>]*background-color:#ffffff[^>]*color:#4a454d[^>]*>/);
  assert.match(template, /data-protected-section="system-credit"[^>]*><td[^>]*padding:5px 12px[^>]*font-size:8px[^>]*line-height:11px[^>]*white-space:nowrap/);
  assert.ok(template.indexOf('data-protected-section="system-credit"') > template.indexOf('data-protected-section="safety-footer"'));
  assert.match(template, /data-protected-section="system-credit"[\s\S]*?<\/tr>\s*<\/table>\s*<\/td>/);
});

test("the source contains one invisible protected message-number and SHA-256 metadata record", () => {
  assert.equal((template.match(/<!--\s*SRMS-METADATA\b/g) || []).length, 1);
  assert.match(template, /<!-- SRMS-METADATA message-number="CHEM-SR-00000000" sha256="PENDING-SHA256" -->/);
  assert.doesNotMatch(template, /data-message-hash/);
});

test("missing, duplicated or crossed structural tags are rejected", () => {
  assert.equal(hasCompleteEmailDocumentStructure(template.replace("</body>", "")), false);
  assert.equal(hasCompleteEmailDocumentStructure(template.replace("<body ", "<body><body ")), false);
  assert.equal(hasCompleteEmailDocumentStructure(template.replace("</td></tr>", "</tr></td>")), false);
  assert.equal(hasCompleteEmailDocumentStructure(template.replace("</table>", "")), false);
});
