import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { hasCompleteEmailDocumentStructure } from "../src/emailUtils.js";

const template = readFileSync(new URL("../src/templates/student-union-announcement.html", import.meta.url), "utf8");

test("the production email template has a complete balanced document structure", () => {
  assert.equal(hasCompleteEmailDocumentStructure(template), true);
});

test("the mail-system credit is a protected final row outside the purple footer", () => {
  const credit = 'This mail is generated by Student Representative Mail System';
  assert.equal((template.match(new RegExp(credit, "g")) || []).length, 1);
  assert.match(template, /data-protected-section="system-credit"/);
  assert.match(template, /data-protected-section="system-credit"[^>]*><td[^>]*background-color:#ffffff[^>]*color:#4a454d[^>]*>/);
  assert.ok(template.indexOf('data-protected-section="system-credit"') > template.indexOf('data-protected-section="safety-footer"'));
  assert.match(template, /data-protected-section="system-credit"[\s\S]*?<\/tr>\s*<\/table>\s*<\/td>/);
});

test("missing, duplicated or crossed structural tags are rejected", () => {
  assert.equal(hasCompleteEmailDocumentStructure(template.replace("</body>", "")), false);
  assert.equal(hasCompleteEmailDocumentStructure(template.replace("<body ", "<body><body ")), false);
  assert.equal(hasCompleteEmailDocumentStructure(template.replace("</td></tr>", "</tr></td>")), false);
  assert.equal(hasCompleteEmailDocumentStructure(template.replace("</table>", "")), false);
});
