export const EMAIL_PRESETS = [
  {
    id: "survey",
    label: "Questionnaire",
    description: "Feedback request without a venue table.",
    subject: "Department of Chemistry Student Representatives | Student questionnaire",
    filename: "manchester-chemistry-student-questionnaire.html",
    modules: { details: false, keyPoints: true, cta: true, followUp: true, contacts: true },
    content: {
      category: "STUDENT FEEDBACK · QUESTIONNAIRE",
      headline: "Tell us about your Chemistry experience",
      summary: "Your feedback helps us represent students and raise shared priorities with the Department of Chemistry.",
      introPrimary: "The Department of Chemistry Student Representatives are inviting you to complete a short questionnaire about your experience of teaching, learning resources, facilities and student support.",
      introSecondary: "Your responses will help us identify recurring themes and prepare evidence-based feedback for departmental discussions. Please avoid including sensitive personal information or details that identify another person.",
      keyPointsHeading: "Why take part?",
      keyPoints: [
        ["Quick to complete", "The questionnaire should take only a few minutes."],
        ["Student-led", "Responses will be reviewed by the Student Representatives."],
        ["Focused on action", "We will use recurring themes to raise priorities and request follow-up where appropriate."],
      ],
      buttonLabel: "Complete the questionnaire →",
      followUp: "Thank you for taking the time to share your views. If the button does not open, contact either Student Representative below for the questionnaire link.",
      facts: [
        ["CLOSES", "See the closing date shown on the questionnaire"],
        ["TIME NEEDED", "A few minutes"],
        ["RESPONSE", "Please do not include sensitive personal information"],
        ["AUDIENCE", "Department of Chemistry students"],
      ],
    },
  },
  {
    id: "event",
    label: "Event",
    description: "Briefing, meeting or social with full details.",
    subject: "Department of Chemistry Student Representatives | Student Feedback Forum",
    filename: "manchester-chemistry-student-feedback-forum.html",
    modules: { details: true, keyPoints: true, cta: true, followUp: true, contacts: true },
    content: {
      category: "CHEMISTRY STUDENT EVENT",
      headline: "Chemistry Student Feedback Forum",
      summary: "Join the Student Representatives to discuss current priorities and share suggestions for the Department of Chemistry.",
      introPrimary: "We would like to invite all Department of Chemistry students to our next Student Feedback Forum. The session is an opportunity to share your experience, discuss common concerns and suggest practical improvements.",
      introSecondary: "The discussion will be informal and student-led. You are welcome to attend for the full session or join briefly to raise a specific point. No previous involvement in student representation is required.",
      keyPointsHeading: "What you need to know",
      keyPoints: [
        ["Share your experience", "Tell us what is working well and where students would benefit from change."],
        ["Hear current updates", "We will summarise the main issues currently being raised by students."],
        ["Help set priorities", "Your contributions will help guide the topics we take forward in departmental discussions."],
      ],
      buttonLabel: "Register or view details →",
      followUp: "If you cannot attend, you can still send feedback to either Student Representative below and we will include it in the discussion.",
      facts: [
        ["DATE", "[EVENT DATE]"],
        ["TIME", "[START–END TIME]"],
        ["LOCATION", "[ROOM OR ONLINE LINK]"],
        ["AUDIENCE", "Department of Chemistry students"],
      ],
    },
  },
  {
    id: "recruitment",
    label: "Recruitment",
    description: "Applications for representatives or volunteers.",
    subject: "Department of Chemistry Student Representatives | Applications open",
    filename: "manchester-chemistry-recruitment.html",
    modules: { details: true, keyPoints: true, cta: true, followUp: true, contacts: true },
    content: {
      category: "STUDENT OPPORTUNITY · RECRUITMENT",
      headline: "Become a Chemistry Student Representative",
      summary: "Help strengthen the student voice and contribute to positive change across the Department of Chemistry.",
      introPrimary: "We are inviting expressions of interest from students who would like to become Student Representatives for the Department of Chemistry. Representatives gather feedback, identify shared priorities and communicate the student perspective in departmental discussions.",
      introSecondary: "The role is a valuable opportunity to develop communication, teamwork and leadership experience while helping improve the student experience. Guidance and support will be available throughout the role.",
      keyPointsHeading: "About the opportunity",
      keyPoints: [
        ["Represent students", "Listen to your peers and communicate shared priorities clearly."],
        ["Work constructively", "Take part in relevant meetings and help develop practical responses to student feedback."],
        ["Build useful experience", "Develop confidence in communication, consultation and collaborative decision-making."],
      ],
      buttonLabel: "Submit an expression of interest →",
      followUp: "If you would like to discuss the role before applying, contact Rongzhi Wu or Wenqian Zhang using the details below.",
      facts: [
        ["DEADLINE", "[APPLICATION DEADLINE]"],
        ["ROLE", "Student Representative"],
        ["COMMITMENT", "[EXPECTED TIME COMMITMENT]"],
        ["ELIGIBILITY", "Current Department of Chemistry students"],
      ],
    },
  },
  {
    id: "deadline",
    label: "Deadline",
    description: "A focused reminder with one required action.",
    subject: "Department of Chemistry Student Representatives | Deadline reminder",
    filename: "manchester-chemistry-deadline-reminder.html",
    modules: { details: true, keyPoints: false, cta: true, followUp: true, contacts: true },
    content: {
      category: "ACTION REQUIRED · DEADLINE REMINDER",
      headline: "Reminder: student action required",
      summary: "Please complete [REQUIRED ACTION] by [DEADLINE].",
      introPrimary: "This is a reminder for [AFFECTED STUDENT GROUP] to complete [REQUIRED ACTION] by [DEADLINE]. Please allow enough time to review the information and submit everything required.",
      introSecondary: "Before submitting, check that your details are accurate and keep any confirmation email or reference number for your records. If you need support, use the official contact or guidance listed below before the deadline.",
      keyPointsHeading: "Important information",
      keyPoints: [
        ["Complete every required field", "Review the form or task carefully before submitting."],
        ["Keep confirmation", "Save the confirmation email, receipt or reference number."],
        ["Ask for help early", "Contact the relevant support team before the deadline if anything is unclear."],
      ],
      buttonLabel: "Complete the required action →",
      followUp: "If you believe this reminder does not apply to you, check the official guidance or contact the relevant support team before taking further action.",
      facts: [
        ["DEADLINE", "[DEADLINE]"],
        ["ACTION", "[REQUIRED ACTION]"],
        ["APPLIES TO", "[AFFECTED STUDENT GROUP]"],
        ["SUPPORT", "[OFFICIAL SUPPORT CONTACT OR PAGE]"],
      ],
    },
  },
  {
    id: "general",
    label: "General notice",
    description: "Simple update with no table or button.",
    subject: "Department of Chemistry Student Representatives | Student notice",
    filename: "manchester-chemistry-student-notice.html",
    modules: { details: false, keyPoints: false, cta: false, followUp: true, contacts: true },
    content: {
      category: "CHEMISTRY STUDENT NOTICE",
      headline: "How to share feedback with your Student Representatives",
      summary: "Contact us about teaching, learning resources, facilities, student support or any shared concern affecting Chemistry students.",
      introPrimary: "The Department of Chemistry Student Representatives are here to listen to students and communicate shared priorities in departmental discussions. We welcome feedback about your academic experience, learning resources, facilities and access to student support.",
      introSecondary: "When contacting us, please explain the issue, how it affects students and any outcome you would like us to consider. We may combine similar feedback into broader themes so that common concerns can be raised clearly and constructively.",
      keyPointsHeading: "How we can help",
      keyPoints: [
        ["Listen", "Receive feedback and identify themes shared by students."],
        ["Represent", "Raise appropriate issues through departmental channels."],
        ["Follow up", "Share updates where further information or action is available."],
      ],
      buttonLabel: "Contact the Student Representatives →",
      followUp: "You can contact Rongzhi Wu or Wenqian Zhang using the email addresses below. Please do not send urgent welfare or safety concerns by this route; use the appropriate University support service instead.",
      facts: [
        ["PURPOSE", "Share feedback with the Student Representatives"],
        ["TOPICS", "Teaching, resources, facilities and student support"],
        ["AUDIENCE", "Department of Chemistry students"],
        ["CONTACT", "Rongzhi Wu or Wenqian Zhang"],
      ],
    },
  },
];

export const DEFAULT_PRESET_ID = "event";

export function getPresetById(id) {
  return EMAIL_PRESETS.find((preset) => preset.id === id) || EMAIL_PRESETS.find((preset) => preset.id === DEFAULT_PRESET_ID);
}
