import {
  extractIntegrityMetadata,
  isValidMessageNumber,
  resetIntegrityMetadata,
} from "../shared/email-integrity.js";

const EDITOR_ATTRIBUTES = [
  "contenteditable",
  "spellcheck",
  "data-mail-studio-editable",
  "data-mail-studio-label",
  "data-mail-studio-region",
  "data-mail-studio-field",
  "aria-label",
];

const EXPORT_ATTRIBUTES = [
  "data-email-module",
  "data-module-enabled",
  "data-contact-index",
  "data-contact-name-index",
  "data-content-block",
  "data-content-block-type",
  "data-content-block-label",
  "data-content-block-core",
  "data-content-block-deleted",
  "data-block-editable",
  "data-protected-section",
  "hidden",
];

export const PRIVACY_NOTICE_URL = "https://mailsys.uomsu.chemvault.science/agreement/privacy-notice/";
export const HIDDEN_CREDIT = "Generated by the Student Representatives Team, The University of Manchester. Technical support provided by Ziwen M.";
export const SYSTEM_CREDIT = "This mail is generated by Student Representative Mail System";
export const INTEGRITY_METADATA_LABEL = "Hidden message number and SHA-256 metadata";

export const PROTECTED_SECTIONS = [
  { id: "brand-header", label: "Department identity and message details" },
  { id: "institution-footer", label: "Department and University footer" },
  { id: "safety-footer", label: "Message verification and privacy footer" },
  { id: "system-credit", label: "Student Representative Mail System credit" },
];

const EMAIL_LAYOUT_GUARDS = [
  {
    selector: 'body > table[role="presentation"]',
    label: "Page-width email background",
    attributes: ["width", "cellspacing", "cellpadding", "border"],
    styles: ["width", "min-width", "max-width", "margin", "padding", "display", "table-layout", "background-color"],
  },
  {
    selector: 'body > table[role="presentation"] > tbody > tr > td',
    label: "Centred email wrapper",
    attributes: ["width", "align", "colspan", "rowspan"],
    styles: ["width", "min-width", "max-width", "margin", "padding", "display", "float", "position"],
  },
  {
    selector: ".email-shell",
    label: "Main email width",
    attributes: ["width", "cellspacing", "cellpadding", "border", "align"],
    styles: ["width", "min-width", "max-width", "margin", "padding", "display", "float", "position", "table-layout", "background-color"],
  },
  {
    selector: ".email-shell > tbody > tr:first-child > td",
    label: "Top accent bar",
    attributes: ["width", "height", "align", "colspan", "rowspan"],
    styles: ["width", "min-width", "max-width", "height", "margin", "padding", "display", "float", "position", "background-color"],
  },
  {
    selector: '[data-protected-section="brand-header"] > td',
    label: "University header container",
    attributes: ["width", "align", "colspan", "rowspan"],
    styles: ["width", "min-width", "max-width", "margin", "padding", "display", "float", "position", "background-color", "border-bottom"],
  },
  {
    selector: '[data-protected-section="brand-header"] > td > table',
    label: "University header columns",
    attributes: ["width", "cellspacing", "cellpadding", "border", "align"],
    styles: ["width", "min-width", "max-width", "margin", "padding", "display", "float", "position", "table-layout"],
  },
  {
    selector: ".email-shell > tbody > tr:nth-child(3) > td",
    label: "Announcement heading container",
    attributes: ["width", "align", "colspan", "rowspan"],
    styles: ["width", "min-width", "max-width", "margin", "padding", "display", "float", "position", "background-color"],
  },
  {
    selector: 'tr[data-email-module="details"] > td',
    label: "Information section container",
    attributes: ["width", "align", "colspan", "rowspan"],
    styles: ["width", "min-width", "max-width", "margin", "padding", "display", "float", "position", "background-color"],
  },
  {
    selector: ".email-body-content",
    label: "Main content column",
    attributes: ["width", "align", "colspan", "rowspan"],
    styles: ["width", "min-width", "max-width", "margin", "padding", "display", "float", "position", "background-color"],
  },
  {
    selector: 'tr[data-email-module="contacts"] > td',
    label: "Contact section container",
    attributes: ["width", "align", "colspan", "rowspan"],
    styles: ["width", "min-width", "max-width", "margin", "padding", "display", "float", "position", "background-color", "border-top"],
  },
  {
    selector: '[data-protected-section="institution-footer"] > td',
    label: "Department footer layout",
    attributes: ["width", "align", "colspan", "rowspan"],
    styles: ["width", "min-width", "max-width", "margin", "padding", "display", "float", "position", "background-color"],
  },
  {
    selector: '[data-protected-section="safety-footer"] > td',
    label: "Verification footer layout",
    attributes: ["width", "align", "colspan", "rowspan"],
    styles: ["width", "min-width", "max-width", "margin", "padding", "display", "float", "position", "background-color"],
  },
  {
    selector: '[data-protected-section="system-credit"] > td',
    label: "System credit layout",
    attributes: ["width", "align", "colspan", "rowspan"],
    styles: ["width", "min-width", "max-width", "margin", "padding", "display", "float", "position", "background-color"],
  },
];

export const EMAIL_MODULES = [
  { id: "intro", label: "Opening copy", description: "Greeting and two introductory paragraphs." },
  { id: "details", label: "Information table", description: "Date, deadline, location or eligibility details." },
  { id: "keyPoints", label: "Key points", description: "Three numbered supporting points." },
  { id: "cta", label: "Action button", description: "Questionnaire, registration or application link." },
  { id: "followUp", label: "Follow-up note", description: "Short guidance below the action area." },
  { id: "signoff", label: "Sign-off", description: "Kind regards and the department identity." },
  { id: "contacts", label: "Contact panel", description: "Both Student Representative email addresses." },
];

export const CONTENT_BLOCK_TYPES = [
  { id: "heading", label: "Heading", description: "A new section title." },
  { id: "paragraph", label: "Paragraph", description: "A standard text paragraph." },
  { id: "bullets", label: "Bullet list", description: "Three editable bullet points." },
  { id: "callout", label: "Callout", description: "A highlighted information box." },
  { id: "divider", label: "Divider", description: "A subtle horizontal rule." },
  { id: "spacer", label: "Spacing", description: "Extra vertical breathing room." },
];

const CONTENT_BLOCK_BUILDERS = {
  heading: ({ id, label }) => `<div data-content-block="${id}" data-content-block-type="heading" data-content-block-label="${label}" data-block-editable="true" style="margin:22px 0 10px 0; font-family:Arial,'Segoe UI',sans-serif; font-size:16px; line-height:22px; font-weight:700; color:#241d27;">Further information</div>`,
  paragraph: ({ id, label }) => `<p data-content-block="${id}" data-content-block-type="paragraph" data-content-block-label="${label}" data-block-editable="true" style="margin:0 0 16px 0; font-family:Arial,'Segoe UI',sans-serif; font-size:12px; line-height:20px; color:#3d3541;">Please review the information above and contact the Student Representatives if you have any questions.</p>`,
  bullets: ({ id, label }) => `<table data-content-block="${id}" data-content-block-type="bullets" data-content-block-label="${label}" role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%; margin:4px 0 18px 0;"><tr><td width="20" valign="top" style="padding:2px 0 7px 0; font-family:Arial,'Segoe UI',sans-serif; font-size:13px; line-height:20px; font-weight:700; color:#660099;">&bull;</td><td data-block-editable="true" valign="top" style="padding:2px 0 7px 0; font-family:Arial,'Segoe UI',sans-serif; font-size:12px; line-height:20px; color:#3d3541;">Review the information above.</td></tr><tr><td width="20" valign="top" style="padding:2px 0 7px 0; font-family:Arial,'Segoe UI',sans-serif; font-size:13px; line-height:20px; font-weight:700; color:#660099;">&bull;</td><td data-block-editable="true" valign="top" style="padding:2px 0 7px 0; font-family:Arial,'Segoe UI',sans-serif; font-size:12px; line-height:20px; color:#3d3541;">Complete any required action before the stated deadline.</td></tr><tr><td width="20" valign="top" style="padding:2px 0 7px 0; font-family:Arial,'Segoe UI',sans-serif; font-size:13px; line-height:20px; font-weight:700; color:#660099;">&bull;</td><td data-block-editable="true" valign="top" style="padding:2px 0 7px 0; font-family:Arial,'Segoe UI',sans-serif; font-size:12px; line-height:20px; color:#3d3541;">Contact the Student Representatives if anything is unclear.</td></tr></table>`,
  callout: ({ id, label }) => `<table data-content-block="${id}" data-content-block-type="callout" data-content-block-label="${label}" role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%; margin:8px 0 20px 0; border:1px solid #dfd4e4; background-color:#f4ebf8;"><tr><td style="padding:15px 18px;"><div data-block-editable="true" style="font-family:Arial,'Segoe UI',sans-serif; font-size:12px; line-height:18px; font-weight:700; color:#660099;">Important</div><div data-block-editable="true" style="padding-top:5px; font-family:Arial,'Segoe UI',sans-serif; font-size:12px; line-height:20px; color:#3d3541;">Please check the details carefully and complete any required action before the stated deadline.</div></td></tr></table>`,
  divider: ({ id, label }) => `<table data-content-block="${id}" data-content-block-type="divider" data-content-block-label="${label}" role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%; margin:22px 0;"><tr><td height="1" style="height:1px; line-height:1px; font-size:0; background-color:#ded9e2;">&nbsp;</td></tr></table>`,
  spacer: ({ id, label }) => `<table data-content-block="${id}" data-content-block-type="spacer" data-content-block-label="${label}" role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%;"><tr><td height="28" style="height:28px; line-height:28px; font-size:0;">&nbsp;</td></tr></table>`,
};

function parseEmail(html) {
  return new DOMParser().parseFromString(html, "text/html");
}

function ensureHiddenCreditInDocument(doc) {
  const walker = doc.createTreeWalker(doc, 128);
  let comment = walker.nextNode();
  while (comment) {
    if ((comment.nodeValue || "").trim() === HIDDEN_CREDIT) return false;
    comment = walker.nextNode();
  }
  doc.documentElement.appendChild(doc.createComment(` ${HIDDEN_CREDIT} `));
  return true;
}

export function ensureHiddenCredit(html) {
  const doc = parseEmail(html);
  if (!ensureHiddenCreditInDocument(doc)) return html;
  return `<!doctype html>\n${doc.documentElement.outerHTML}`;
}

function removeEditorMetadata(doc) {
  doc.getElementById("mail-studio-editor-style")?.remove();
  doc.body?.classList.remove("mail-studio-dragging");
  if (doc.body && !doc.body.className) doc.body.removeAttribute("class");
  doc.querySelectorAll("[data-mail-studio-editor-only]").forEach((element) => element.remove());
  doc.querySelectorAll("*").forEach((element) => {
    EDITOR_ATTRIBUTES.forEach((attribute) => element.removeAttribute(attribute));
    if (element.getAttribute("role") === "textbox") element.removeAttribute("role");
  });
}

function removeDisabledModules(doc) {
  doc.querySelectorAll('[data-email-module][data-module-enabled="false"]').forEach((node) => node.remove());
}

function removeDeletedContentBlocks(doc) {
  doc.querySelectorAll('[data-content-block-deleted="true"]').forEach((node) => node.remove());
}

function removeExportMetadata(doc) {
  doc.querySelectorAll("*").forEach((element) => {
    EXPORT_ATTRIBUTES.forEach((attribute) => element.removeAttribute(attribute));
  });
}

function setModuleEnabled(doc, moduleId, enabled) {
  doc.querySelectorAll(`[data-email-module="${moduleId}"]`).forEach((element) => {
    element.dataset.moduleEnabled = enabled ? "true" : "false";
    if (enabled) {
      element.removeAttribute("data-content-block-deleted");
      element.removeAttribute("hidden");
      element.style.removeProperty("display");
      const style = (element.getAttribute("style") || "")
        .replace(/(?:^|;)\s*mso-hide\s*:[^;]*/gi, "")
        .replace(/^\s*;|;\s*$/g, "")
        .trim();
      if (style) element.setAttribute("style", style);
      else element.removeAttribute("style");
      return;
    }

    element.setAttribute("hidden", "");
    element.style.setProperty("display", "none", "important");
    const style = element.getAttribute("style") || "";
    if (!/mso-hide\s*:/i.test(style)) element.setAttribute("style", `${style} mso-hide:all;`.trim());
  });
}

function setText(doc, selector, value) {
  const element = doc.querySelector(selector);
  if (element && typeof value === "string") element.textContent = value;
}

export function deriveContactName(email) {
  const prefix = String(email || "").trim().split("@")[0] || "";
  const words = prefix
    .replace(/\d+/g, "")
    .split(/[._-]+/)
    .map((word) => word.replace(/[^a-zA-Z']/g, ""))
    .filter(Boolean)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase());
  return words.join(" ") || "Student Representative";
}

function updateContactName(doc, emailElement, index, email) {
  if (!emailElement) return false;
  const displayName = deriveContactName(email);
  const container = emailElement.closest("div");
  let nameElement = doc.querySelector(`[data-contact-name-index="${index}"]`) || container?.querySelector("strong");

  if (nameElement) {
    nameElement.dataset.contactNameIndex = String(index);
    if (nameElement.textContent.trim() === displayName) return false;
    nameElement.textContent = displayName;
    return true;
  }

  const genericTextNode = [...(container?.childNodes || [])].find((node) => (
    node.nodeType === 3 && /Student Representative\s*\d*/i.test(node.nodeValue || "")
  ));
  if (!genericTextNode) return false;

  nameElement = doc.createElement("strong");
  nameElement.dataset.contactNameIndex = String(index);
  nameElement.setAttribute("style", "color:#2b2430;");
  nameElement.textContent = displayName;
  genericTextNode.replaceWith(nameElement, doc.createTextNode(" · Student Representative"));
  return true;
}

function normaliseContactNamesInDocument(doc) {
  let changed = false;
  [1, 2].forEach((index) => {
    const emailElement = doc.querySelector(`[data-contact-index="${index}"]`) || doc.querySelectorAll('a[href^="mailto:"]')[index - 1];
    if (!emailElement) return;
    const email = (emailElement.getAttribute("href") || "").replace(/^mailto:/i, "") || emailElement.textContent.trim();
    if (updateContactName(doc, emailElement, index, email)) changed = true;
  });
  return changed;
}

export function normaliseContactNames(html) {
  const doc = parseEmail(html);
  if (!normaliseContactNamesInDocument(doc)) return html;
  return `<!doctype html>\n${doc.documentElement.outerHTML}`;
}

function removeUnsafeContent(doc) {
  doc.querySelectorAll("script, iframe, frame, form, input, button, object, embed, base, meta[http-equiv]").forEach((node) => node.remove());
  doc.querySelectorAll("*").forEach((element) => {
    [...element.attributes].forEach((attribute) => {
      if (attribute.name.toLowerCase().startsWith("on")) element.removeAttribute(attribute.name);
    });
  });
  doc.querySelectorAll("a[href]").forEach((anchor) => {
    const href = anchor.getAttribute("href")?.trim() || "";
    if (/^(javascript|data|vbscript):/i.test(href)) anchor.removeAttribute("href");
  });
  doc.querySelectorAll("img[src]").forEach((image) => {
    const src = image.getAttribute("src")?.trim() || "";
    if (src && !/^https:\/\//i.test(src) && !/^cid:/i.test(src)) image.removeAttribute("src");
  });
}

export function hasCompleteEmailDocumentStructure(html) {
  if (typeof html !== "string" || !/^\s*<!doctype\s+html[\s>]/i.test(html)) return false;
  const source = html.replace(/<!--[\s\S]*?-->/g, "");
  const structuralTags = new Set(["html", "head", "body", "table", "tbody", "tr", "td", "th"]);
  const requiredTags = new Set(["html", "head", "body"]);
  const openingCounts = new Map([...requiredTags].map((tag) => [tag, 0]));
  const closingCounts = new Map([...requiredTags].map((tag) => [tag, 0]));
  const stack = [];

  for (const match of source.matchAll(/<(\/)?([a-z][a-z0-9-]*)\b[^>]*>/gi)) {
    const tag = match[2].toLowerCase();
    if (!structuralTags.has(tag)) continue;
    if (match[1]) {
      if (stack.at(-1) !== tag) return false;
      stack.pop();
      if (requiredTags.has(tag)) closingCounts.set(tag, closingCounts.get(tag) + 1);
      continue;
    }
    stack.push(tag);
    if (requiredTags.has(tag)) openingCounts.set(tag, openingCounts.get(tag) + 1);
  }

  return stack.length === 0 && [...requiredTags].every((tag) => (
    openingCounts.get(tag) === 1 && closingCounts.get(tag) === 1
  ));
}

export function isUsableEmailHtml(html) {
  if (!hasCompleteEmailDocumentStructure(html)) return false;
  const doc = parseEmail(html);
  const shells = doc.querySelectorAll(".email-shell");
  return shells.length === 1 && shells[0].tagName === "TABLE";
}

export function getProtectedContentIssues(html) {
  if (typeof html !== "string") return [...PROTECTED_SECTIONS.map((section) => section.label), INTEGRITY_METADATA_LABEL];
  const doc = parseEmail(html);
  const issues = [];
  const brand = doc.querySelector('[data-protected-section="brand-header"]');
  const institutionFooter = doc.querySelector('[data-protected-section="institution-footer"]');
  const safetyFooter = doc.querySelector('[data-protected-section="safety-footer"]');
  const systemCredit = doc.querySelector('[data-protected-section="system-credit"]');

  if (!brand) {
    issues.push(PROTECTED_SECTIONS[0].label);
  } else {
    const departmentName = brand.querySelector(".department-label .department-name")?.textContent.trim() || "";
    const representativeName = brand.querySelector(".department-label .representative-name")?.textContent.trim() || "";
    const messageNumber = brand.querySelector('[data-message-number="true"]')?.textContent.trim() || "";
    const containsBrandImage = Boolean(brand.querySelector("img"));
    if (containsBrandImage || departmentName !== "Department of Chemistry" || representativeName !== "Student Representatives" || !isValidMessageNumber(messageNumber)) {
      issues.push(PROTECTED_SECTIONS[0].label);
    }
  }

  if (!institutionFooter) {
    issues.push(PROTECTED_SECTIONS[1].label);
  } else {
    const text = institutionFooter.textContent.replace(/\s+/g, " ").trim();
    const chemistryLink = institutionFooter.querySelector('a[href="https://www.chemistry.manchester.ac.uk/"]');
    if (!text.includes("Department of Chemistry · Student Representatives") || !text.includes("The University of Manchester") || !text.includes("M13 9PL") || !chemistryLink) {
      issues.push(PROTECTED_SECTIONS[1].label);
    }
  }

  if (!safetyFooter) {
    issues.push(PROTECTED_SECTIONS[2].label);
  } else {
    const privacyLink = safetyFooter.querySelector(`a[href="${PRIVACY_NOTICE_URL}"]`);
    const verificationCode = safetyFooter.querySelector('[data-verification-code="true"]');
    const footerMessageNumber = safetyFooter.querySelector('[data-message-number-copy="true"]')?.textContent.trim() || "";
    const primaryMessageNumber = brand?.querySelector('[data-message-number="true"]')?.textContent.trim() || "";
    const verificationLink = safetyFooter.querySelector('a[href="https://uom-su-mail-system.pages.dev/verify/"]');
    const text = safetyFooter.textContent.replace(/\s+/g, " ").trim();
    if (!privacyLink || !verificationCode || footerMessageNumber !== primaryMessageNumber || !verificationLink || !text.includes("Verification code") || !text.includes("contact a Student Representative") || !text.includes("Submitted form responses may be analysed by the Student Representatives Team")) {
      issues.push(PROTECTED_SECTIONS[2].label);
    }
  }

  if (!systemCredit) {
    issues.push(PROTECTED_SECTIONS[3].label);
  } else {
    const creditCell = systemCredit.querySelector("td");
    const text = systemCredit.textContent.replace(/\s+/g, " ").trim();
    const style = (creditCell?.getAttribute("style") || "").replace(/\s+/g, "").toLowerCase();
    const shellBody = doc.querySelector(".email-shell > tbody");
    if (text !== SYSTEM_CREDIT || !style.includes("color:#4a454d") || !style.includes("background-color:#ffffff") || shellBody?.lastElementChild !== systemCredit || systemCredit.previousElementSibling !== safetyFooter) {
      issues.push(PROTECTED_SECTIONS[3].label);
    }
  }

  try {
    const metadata = extractIntegrityMetadata(html);
    const primaryMessageNumber = brand?.querySelector('[data-message-number="true"]')?.textContent.trim() || "";
    if (metadata.messageNumber !== primaryMessageNumber) issues.push(INTEGRITY_METADATA_LABEL);
  } catch {
    issues.push(INTEGRITY_METADATA_LABEL);
  }

  return issues;
}

function normaliseLayoutValue(value) {
  return String(value || "").replace(/\s+/g, " ").trim().toLowerCase();
}

function layoutGuardMatches(current, canonical, guard) {
  if (!current || !canonical || current.tagName !== canonical.tagName) return false;
  const attributesMatch = guard.attributes.every((attribute) => (
    normaliseLayoutValue(current.getAttribute(attribute)) === normaliseLayoutValue(canonical.getAttribute(attribute))
  ));
  if (!attributesMatch) return false;
  return guard.styles.every((property) => (
    normaliseLayoutValue(current.style.getPropertyValue(property)) === normaliseLayoutValue(canonical.style.getPropertyValue(property))
    && current.style.getPropertyPriority(property) === canonical.style.getPropertyPriority(property)
  ));
}

export function getEmailLayoutIssues(html, canonicalHtml) {
  if (typeof html !== "string" || typeof canonicalHtml !== "string") return ["Core email layout"];
  const doc = parseEmail(html);
  const canonical = parseEmail(canonicalHtml);
  return EMAIL_LAYOUT_GUARDS
    .filter((guard) => !layoutGuardMatches(
      doc.querySelector(guard.selector),
      canonical.querySelector(guard.selector),
      guard,
    ))
    .map((guard) => guard.label);
}

export function restoreEmailLayout(html, canonicalHtml) {
  if (typeof html !== "string" || typeof canonicalHtml !== "string") return canonicalHtml;
  const doc = parseEmail(html);
  const canonical = parseEmail(canonicalHtml);

  for (const guard of EMAIL_LAYOUT_GUARDS) {
    const current = doc.querySelector(guard.selector);
    const source = canonical.querySelector(guard.selector);
    if (!current || !source || current.tagName !== source.tagName) return canonicalHtml;

    guard.attributes.forEach((attribute) => {
      const value = source.getAttribute(attribute);
      if (value === null) current.removeAttribute(attribute);
      else current.setAttribute(attribute, value);
    });
    guard.styles.forEach((property) => {
      const value = source.style.getPropertyValue(property);
      if (!value) current.style.removeProperty(property);
      else current.style.setProperty(property, value, source.style.getPropertyPriority(property));
    });
  }

  return resetIntegrityMetadata(`<!doctype html>\n${doc.documentElement.outerHTML}`);
}

export function restoreProtectedContent(html, canonicalHtml) {
  const doc = parseEmail(html);
  const canonical = parseEmail(canonicalHtml);
  const shellBody = doc.querySelector(".email-shell > tbody");
  if (!shellBody) return canonicalHtml;

  PROTECTED_SECTIONS.forEach((section) => {
    const selector = `[data-protected-section="${section.id}"]`;
    const source = canonical.querySelector(selector);
    if (!source) return;
    const replacement = doc.importNode(source, true);
    const current = doc.querySelector(selector);
    if (current) {
      current.replaceWith(replacement);
      return;
    }

    if (section.id === "brand-header") {
      shellBody.children[0]?.after(replacement);
      return;
    }
    if (section.id === "institution-footer") {
      const safety = doc.querySelector('[data-protected-section="safety-footer"]');
      if (safety) shellBody.insertBefore(replacement, safety);
      else shellBody.appendChild(replacement);
      return;
    }
    if (section.id === "safety-footer") {
      const credit = doc.querySelector('[data-protected-section="system-credit"]');
      if (credit) shellBody.insertBefore(replacement, credit);
      else shellBody.appendChild(replacement);
      return;
    }
    shellBody.appendChild(replacement);
  });

  ["institution-footer", "safety-footer", "system-credit"].forEach((sectionId) => {
    const footer = doc.querySelector(`[data-protected-section="${sectionId}"]`);
    if (footer) shellBody.appendChild(footer);
  });

  return resetIntegrityMetadata(`<!doctype html>\n${doc.documentElement.outerHTML}`);
}

export function serializeEmailDocument(sourceDocument) {
  const doc = parseEmail(`<!doctype html>${sourceDocument.documentElement.outerHTML}`);
  normaliseContactNamesInDocument(doc);
  removeEditorMetadata(doc);
  ensureHiddenCreditInDocument(doc);
  return resetIntegrityMetadata(`<!doctype html>\n${doc.documentElement.outerHTML}`);
}

export function cleanEmailHtml(html) {
  const doc = parseEmail(html);
  normaliseContactNamesInDocument(doc);
  removeDeletedContentBlocks(doc);
  removeDisabledModules(doc);
  removeEditorMetadata(doc);
  removeExportMetadata(doc);
  removeUnsafeContent(doc);
  ensureHiddenCreditInDocument(doc);
  return resetIntegrityMetadata(`<!doctype html>\n${doc.documentElement.outerHTML}`);
}

export function getEmailModules(html) {
  const doc = parseEmail(html);
  return Object.fromEntries(EMAIL_MODULES.map((module) => {
    const nodes = [...doc.querySelectorAll(`[data-email-module="${module.id}"]`)];
    const enabled = nodes.length > 0 && nodes.some((node) => node.dataset.moduleEnabled !== "false" && node.dataset.contentBlockDeleted !== "true" && !node.hasAttribute("hidden"));
    return [module.id, enabled];
  }));
}

export function getContentBlocks(html) {
  const doc = parseEmail(html);
  return [...doc.querySelectorAll("[data-content-block]")]
    .filter((element) => element.dataset.contentBlockDeleted !== "true")
    .map((element) => ({
      id: element.dataset.contentBlock,
      type: element.dataset.contentBlockType || "content",
      label: element.dataset.contentBlockLabel || "Content block",
      core: element.dataset.contentBlockCore === "true",
    }));
}

export function addContentBlock(html, type, blockId, placement = {}) {
  const doc = parseEmail(html);
  const definition = CONTENT_BLOCK_TYPES.find((item) => item.id === type);
  const builder = CONTENT_BLOCK_BUILDERS[type];
  const destination = doc.querySelector(".email-body-content");
  if (!definition || !builder || !destination) return html;

  const safeId = String(blockId || `block-${Date.now()}`).replace(/[^a-z0-9_-]/gi, "-");
  const template = doc.createElement("template");
  template.innerHTML = builder({ id: safeId, label: definition.label });
  const block = template.content.firstElementChild;
  const beforeBlock = placement.beforeBlockId
    ? destination.querySelector(`[data-content-block="${CSS.escape(placement.beforeBlockId)}"]`)
    : null;
  if (beforeBlock) {
    destination.insertBefore(block, beforeBlock);
    return `<!doctype html>\n${doc.documentElement.outerHTML}`;
  }
  if (placement.atEnd) {
    destination.appendChild(block);
    return `<!doctype html>\n${doc.documentElement.outerHTML}`;
  }
  const signoff = destination.querySelector('.signoff[data-content-block]');
  destination.insertBefore(block, signoff || null);
  return `<!doctype html>\n${doc.documentElement.outerHTML}`;
}

export function repositionContentBlock(html, blockId, beforeBlockId = null) {
  const doc = parseEmail(html);
  const destination = doc.querySelector(".email-body-content");
  const block = destination?.querySelector(`[data-content-block="${CSS.escape(blockId)}"]`);
  if (!destination || !block) return html;

  if (beforeBlockId) {
    const beforeBlock = destination.querySelector(`[data-content-block="${CSS.escape(beforeBlockId)}"]`);
    if (!beforeBlock || beforeBlock === block) return html;
    destination.insertBefore(block, beforeBlock);
  } else {
    destination.appendChild(block);
  }

  return `<!doctype html>\n${doc.documentElement.outerHTML}`;
}

export function removeContentBlock(html, blockId) {
  const doc = parseEmail(html);
  const block = doc.querySelector(`[data-content-block="${CSS.escape(blockId)}"]`);
  if (!block) return html;
  block.dataset.contentBlockDeleted = "true";
  block.setAttribute("hidden", "");
  block.style.setProperty("display", "none", "important");
  const style = block.getAttribute("style") || "";
  if (!/mso-hide\s*:/i.test(style)) block.setAttribute("style", `${style} mso-hide:all;`.trim());
  return `<!doctype html>\n${doc.documentElement.outerHTML}`;
}

export function moveContentBlock(html, blockId, direction) {
  const doc = parseEmail(html);
  const block = doc.querySelector(`[data-content-block="${CSS.escape(blockId)}"]`);
  const parent = block?.parentElement;
  if (!block || !parent) return html;
  const siblings = [...parent.children].filter((element) => element.hasAttribute("data-content-block") && element.dataset.contentBlockDeleted !== "true");
  const index = siblings.indexOf(block);
  if (direction === "up" && index > 0) parent.insertBefore(block, siblings[index - 1]);
  if (direction === "down" && index >= 0 && index < siblings.length - 1) parent.insertBefore(siblings[index + 1], block);
  return `<!doctype html>\n${doc.documentElement.outerHTML}`;
}

export function updateEmailModules(html, changes) {
  const doc = parseEmail(html);
  EMAIL_MODULES.forEach((module) => {
    if (Object.hasOwn(changes, module.id)) setModuleEnabled(doc, module.id, Boolean(changes[module.id]));
  });
  return `<!doctype html>\n${doc.documentElement.outerHTML}`;
}

export function applyEmailPreset(html, preset) {
  const doc = parseEmail(html);
  const content = preset.content || {};

  doc.title = preset.subject || doc.title;
  setText(doc, ".preheader", content.summary);
  setText(doc, ".category", content.category);
  setText(doc, ".headline", content.headline);
  setText(doc, ".summary", content.summary);
  setText(doc, ".intro-primary", content.introPrimary);
  setText(doc, ".intro-secondary", content.introSecondary);
  setText(doc, ".key-points-heading", content.keyPointsHeading);
  setText(doc, ".button-link", content.buttonLabel);
  setText(doc, ".follow-up-copy", content.followUp);

  if (Array.isArray(content.facts)) {
    const labels = doc.querySelectorAll(".fact-label");
    const values = doc.querySelectorAll(".fact-value");
    content.facts.forEach(([label, value], index) => {
      if (labels[index]) labels[index].textContent = label;
      if (values[index]) values[index].textContent = value;
    });
  }

  if (Array.isArray(content.keyPoints)) {
    const titles = doc.querySelectorAll(".key-point-title");
    const details = doc.querySelectorAll(".key-point-detail");
    content.keyPoints.forEach(([title, detail], index) => {
      if (titles[index]) titles[index].textContent = title;
      if (details[index]) details[index].textContent = detail;
    });
  }

  EMAIL_MODULES.forEach((module) => {
    setModuleEnabled(doc, module.id, preset.modules?.[module.id] !== false);
  });

  return `<!doctype html>\n${doc.documentElement.outerHTML}`;
}

export function getEmailMetadata(html) {
  const doc = parseEmail(html);
  const cta = doc.querySelector(".button-link");
  const email1 = doc.querySelector('[data-contact-index="1"]') || doc.querySelectorAll('a[href^="mailto:"]')[0];
  const email2 = doc.querySelector('[data-contact-index="2"]') || doc.querySelectorAll('a[href^="mailto:"]')[1];
  return {
    ctaUrl: cta?.getAttribute("href") || "",
    contactEmail1: (email1?.getAttribute("href") || "").replace(/^mailto:/i, "") || email1?.textContent?.trim() || "",
    contactEmail2: (email2?.getAttribute("href") || "").replace(/^mailto:/i, "") || email2?.textContent?.trim() || "",
  };
}

export function updateEmailMetadata(html, changes) {
  const doc = parseEmail(html);
  if (Object.hasOwn(changes, "ctaUrl")) {
    doc.querySelector(".button-link")?.setAttribute("href", changes.ctaUrl.trim());
  }
  [1, 2].forEach((index) => {
    const key = `contactEmail${index}`;
    if (!Object.hasOwn(changes, key)) return;
    const email = doc.querySelector(`[data-contact-index="${index}"]`) || doc.querySelectorAll('a[href^="mailto:"]')[index - 1];
    if (!email) return;
    const value = changes[key].trim();
    email.setAttribute("href", `mailto:${value}`);
    email.textContent = value;
    updateContactName(doc, email, index, value);
  });
  return `<!doctype html>\n${doc.documentElement.outerHTML}`;
}
