const EDITOR_ATTRIBUTES = [
  "contenteditable",
  "spellcheck",
  "data-mail-studio-editable",
  "data-mail-studio-label",
  "data-mail-studio-region",
  "data-mail-studio-field",
  "aria-label",
];

const EXPORT_ATTRIBUTES = [
  "data-email-module",
  "data-module-enabled",
  "data-contact-index",
  "data-contact-name-index",
  "data-content-block",
  "data-content-block-type",
  "data-content-block-label",
  "data-content-block-core",
  "data-content-block-deleted",
  "data-block-editable",
  "data-protected-section",
  "hidden",
];

const OFFICIAL_LOGO_URL = "https://assets.manchester.ac.uk/logos/hi-res/TAB_UNI_MAIN_logo/White_backgrounds/TAB_col_white_background.png";
const SAFETY_URL = "https://www.studentsupport.manchester.ac.uk/finances/financial-wellbeing/mypages/risks/";
export const PRIVACY_NOTICE_URL = "https://mailsys.uomsu.chemvault.science/agreement/privacy-notice/";
export const HIDDEN_CREDIT = "Generated by the Student Representatives Team, The University of Manchester. Technical support provided by Ziwen M.";

export const PROTECTED_SECTIONS = [
  { id: "brand-header", label: "University logo and department header" },
  { id: "institution-footer", label: "Department and University footer" },
  { id: "safety-footer", label: "University email-safety footer" },
];

export const EMAIL_MODULES = [
  { id: "intro", label: "Opening copy", description: "Greeting and two introductory paragraphs." },
  { id: "details", label: "Information table", description: "Date, deadline, location or eligibility details." },
  { id: "keyPoints", label: "Key points", description: "Three numbered supporting points." },
  { id: "cta", label: "Action button", description: "Questionnaire, registration or application link." },
  { id: "followUp", label: "Follow-up note", description: "Short guidance below the action area." },
  { id: "signoff", label: "Sign-off", description: "Kind regards and the department identity." },
  { id: "contacts", label: "Contact panel", description: "Both Student Representative email addresses." },
];

export const CONTENT_BLOCK_TYPES = [
  { id: "heading", label: "Heading", description: "A new section title." },
  { id: "paragraph", label: "Paragraph", description: "A standard text paragraph." },
  { id: "bullets", label: "Bullet list", description: "Three editable bullet points." },
  { id: "callout", label: "Callout", description: "A highlighted information box." },
  { id: "divider", label: "Divider", description: "A subtle horizontal rule." },
  { id: "spacer", label: "Spacing", description: "Extra vertical breathing room." },
];

const CONTENT_BLOCK_BUILDERS = {
  heading: ({ id, label }) => `<div data-content-block="${id}" data-content-block-type="heading" data-content-block-label="${label}" data-block-editable="true" style="margin:24px 0 12px 0; font-family:Arial,'Segoe UI',sans-serif; font-size:20px; line-height:28px; font-weight:700; color:#241d27;">Further information</div>`,
  paragraph: ({ id, label }) => `<p data-content-block="${id}" data-content-block-type="paragraph" data-content-block-label="${label}" data-block-editable="true" style="margin:0 0 18px 0; font-family:Arial,'Segoe UI',sans-serif; font-size:15px; line-height:27px; color:#3d3541;">Please review the information above and contact the Student Representatives if you have any questions.</p>`,
  bullets: ({ id, label }) => `<table data-content-block="${id}" data-content-block-type="bullets" data-content-block-label="${label}" role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%; margin:4px 0 20px 0;"><tr><td width="22" valign="top" style="padding:3px 0 9px 0; font-family:Arial,'Segoe UI',sans-serif; font-size:16px; line-height:24px; font-weight:700; color:#660099;">&bull;</td><td data-block-editable="true" valign="top" style="padding:3px 0 9px 0; font-family:Arial,'Segoe UI',sans-serif; font-size:15px; line-height:24px; color:#3d3541;">Review the information above.</td></tr><tr><td width="22" valign="top" style="padding:3px 0 9px 0; font-family:Arial,'Segoe UI',sans-serif; font-size:16px; line-height:24px; font-weight:700; color:#660099;">&bull;</td><td data-block-editable="true" valign="top" style="padding:3px 0 9px 0; font-family:Arial,'Segoe UI',sans-serif; font-size:15px; line-height:24px; color:#3d3541;">Complete any required action before the stated deadline.</td></tr><tr><td width="22" valign="top" style="padding:3px 0 9px 0; font-family:Arial,'Segoe UI',sans-serif; font-size:16px; line-height:24px; font-weight:700; color:#660099;">&bull;</td><td data-block-editable="true" valign="top" style="padding:3px 0 9px 0; font-family:Arial,'Segoe UI',sans-serif; font-size:15px; line-height:24px; color:#3d3541;">Contact the Student Representatives if anything is unclear.</td></tr></table>`,
  callout: ({ id, label }) => `<table data-content-block="${id}" data-content-block-type="callout" data-content-block-label="${label}" role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%; margin:8px 0 22px 0; border:1px solid #dfd4e4; background-color:#f4ebf8;"><tr><td style="padding:18px 20px;"><div data-block-editable="true" style="font-family:Arial,'Segoe UI',sans-serif; font-size:15px; line-height:22px; font-weight:700; color:#660099;">Important</div><div data-block-editable="true" style="padding-top:6px; font-family:Arial,'Segoe UI',sans-serif; font-size:14px; line-height:23px; color:#3d3541;">Please check the details carefully and complete any required action before the stated deadline.</div></td></tr></table>`,
  divider: ({ id, label }) => `<table data-content-block="${id}" data-content-block-type="divider" data-content-block-label="${label}" role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%; margin:22px 0;"><tr><td height="1" style="height:1px; line-height:1px; font-size:0; background-color:#ded9e2;">&nbsp;</td></tr></table>`,
  spacer: ({ id, label }) => `<table data-content-block="${id}" data-content-block-type="spacer" data-content-block-label="${label}" role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%;"><tr><td height="28" style="height:28px; line-height:28px; font-size:0;">&nbsp;</td></tr></table>`,
};

function parseEmail(html) {
  return new DOMParser().parseFromString(html, "text/html");
}

function ensureHiddenCreditInDocument(doc) {
  const walker = doc.createTreeWalker(doc, 128);
  let comment = walker.nextNode();
  while (comment) {
    if ((comment.nodeValue || "").trim() === HIDDEN_CREDIT) return false;
    comment = walker.nextNode();
  }
  doc.documentElement.appendChild(doc.createComment(` ${HIDDEN_CREDIT} `));
  return true;
}

export function ensureHiddenCredit(html) {
  const doc = parseEmail(html);
  if (!ensureHiddenCreditInDocument(doc)) return html;
  return `<!doctype html>\n${doc.documentElement.outerHTML}`;
}

function removeEditorMetadata(doc) {
  doc.getElementById("mail-studio-editor-style")?.remove();
  doc.body?.classList.remove("mail-studio-dragging");
  if (doc.body && !doc.body.className) doc.body.removeAttribute("class");
  doc.querySelectorAll("[data-mail-studio-editor-only]").forEach((element) => element.remove());
  doc.querySelectorAll("*").forEach((element) => {
    EDITOR_ATTRIBUTES.forEach((attribute) => element.removeAttribute(attribute));
    if (element.getAttribute("role") === "textbox") element.removeAttribute("role");
  });
}

function removeDisabledModules(doc) {
  doc.querySelectorAll('[data-email-module][data-module-enabled="false"]').forEach((node) => node.remove());
}

function removeDeletedContentBlocks(doc) {
  doc.querySelectorAll('[data-content-block-deleted="true"]').forEach((node) => node.remove());
}

function removeExportMetadata(doc) {
  doc.querySelectorAll("*").forEach((element) => {
    EXPORT_ATTRIBUTES.forEach((attribute) => element.removeAttribute(attribute));
  });
}

function setModuleEnabled(doc, moduleId, enabled) {
  doc.querySelectorAll(`[data-email-module="${moduleId}"]`).forEach((element) => {
    element.dataset.moduleEnabled = enabled ? "true" : "false";
    if (enabled) {
      element.removeAttribute("data-content-block-deleted");
      element.removeAttribute("hidden");
      element.style.removeProperty("display");
      const style = (element.getAttribute("style") || "")
        .replace(/(?:^|;)\s*mso-hide\s*:[^;]*/gi, "")
        .replace(/^\s*;|;\s*$/g, "")
        .trim();
      if (style) element.setAttribute("style", style);
      else element.removeAttribute("style");
      return;
    }

    element.setAttribute("hidden", "");
    element.style.setProperty("display", "none", "important");
    const style = element.getAttribute("style") || "";
    if (!/mso-hide\s*:/i.test(style)) element.setAttribute("style", `${style} mso-hide:all;`.trim());
  });
}

function setText(doc, selector, value) {
  const element = doc.querySelector(selector);
  if (element && typeof value === "string") element.textContent = value;
}

export function deriveContactName(email) {
  const prefix = String(email || "").trim().split("@")[0] || "";
  const words = prefix
    .replace(/\d+/g, "")
    .split(/[._-]+/)
    .map((word) => word.replace(/[^a-zA-Z']/g, ""))
    .filter(Boolean)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase());
  return words.join(" ") || "Student Representative";
}

function updateContactName(doc, emailElement, index, email) {
  if (!emailElement) return false;
  const displayName = deriveContactName(email);
  const container = emailElement.closest("div");
  let nameElement = doc.querySelector(`[data-contact-name-index="${index}"]`) || container?.querySelector("strong");

  if (nameElement) {
    nameElement.dataset.contactNameIndex = String(index);
    if (nameElement.textContent.trim() === displayName) return false;
    nameElement.textContent = displayName;
    return true;
  }

  const genericTextNode = [...(container?.childNodes || [])].find((node) => (
    node.nodeType === 3 && /Student Representative\s*\d*/i.test(node.nodeValue || "")
  ));
  if (!genericTextNode) return false;

  nameElement = doc.createElement("strong");
  nameElement.dataset.contactNameIndex = String(index);
  nameElement.setAttribute("style", "color:#2b2430;");
  nameElement.textContent = displayName;
  genericTextNode.replaceWith(nameElement, doc.createTextNode(" · Student Representative"));
  return true;
}

function normaliseContactNamesInDocument(doc) {
  let changed = false;
  [1, 2].forEach((index) => {
    const emailElement = doc.querySelector(`[data-contact-index="${index}"]`) || doc.querySelectorAll('a[href^="mailto:"]')[index - 1];
    if (!emailElement) return;
    const email = (emailElement.getAttribute("href") || "").replace(/^mailto:/i, "") || emailElement.textContent.trim();
    if (updateContactName(doc, emailElement, index, email)) changed = true;
  });
  return changed;
}

export function normaliseContactNames(html) {
  const doc = parseEmail(html);
  if (!normaliseContactNamesInDocument(doc)) return html;
  return `<!doctype html>\n${doc.documentElement.outerHTML}`;
}

function removeUnsafeContent(doc) {
  doc.querySelectorAll("script, iframe, frame, form, input, button, object, embed, base, meta[http-equiv]").forEach((node) => node.remove());
  doc.querySelectorAll("*").forEach((element) => {
    [...element.attributes].forEach((attribute) => {
      if (attribute.name.toLowerCase().startsWith("on")) element.removeAttribute(attribute.name);
    });
  });
  doc.querySelectorAll("a[href]").forEach((anchor) => {
    const href = anchor.getAttribute("href")?.trim() || "";
    if (/^(javascript|data|vbscript):/i.test(href)) anchor.removeAttribute("href");
  });
  doc.querySelectorAll("img[src]").forEach((image) => {
    const src = image.getAttribute("src")?.trim() || "";
    if (src && !/^https:\/\//i.test(src) && !/^cid:/i.test(src)) image.removeAttribute("src");
  });
}

export function isUsableEmailHtml(html) {
  if (typeof html !== "string" || !/<html[\s>]/i.test(html) || !/<body[\s>]/i.test(html)) return false;
  const doc = parseEmail(html);
  return Boolean(doc.querySelector(".email-shell"));
}

export function getProtectedContentIssues(html) {
  if (typeof html !== "string") return PROTECTED_SECTIONS.map((section) => section.label);
  const doc = parseEmail(html);
  const issues = [];
  const brand = doc.querySelector('[data-protected-section="brand-header"]');
  const institutionFooter = doc.querySelector('[data-protected-section="institution-footer"]');
  const safetyFooter = doc.querySelector('[data-protected-section="safety-footer"]');

  if (!brand) {
    issues.push(PROTECTED_SECTIONS[0].label);
  } else {
    const logo = brand.querySelector(".university-logo");
    const departmentLabel = brand.querySelector(".department-label")?.textContent.replace(/\s+/g, " ").trim() || "";
    if (logo?.getAttribute("src") !== OFFICIAL_LOGO_URL || departmentLabel !== "DEPARTMENT OF CHEMISTRY · STUDENT REPRESENTATIVES") {
      issues.push(PROTECTED_SECTIONS[0].label);
    }
  }

  if (!institutionFooter) {
    issues.push(PROTECTED_SECTIONS[1].label);
  } else {
    const text = institutionFooter.textContent.replace(/\s+/g, " ").trim();
    const chemistryLink = institutionFooter.querySelector('a[href="https://www.chemistry.manchester.ac.uk/"]');
    if (!text.includes("Department of Chemistry · Student Representatives") || !text.includes("The University of Manchester") || !text.includes("M13 9PL") || !chemistryLink) {
      issues.push(PROTECTED_SECTIONS[1].label);
    }
  }

  if (!safetyFooter) {
    issues.push(PROTECTED_SECTIONS[2].label);
  } else {
    const safetyLink = safetyFooter.querySelector(`a[href="${SAFETY_URL}"]`);
    const privacyLink = safetyFooter.querySelector(`a[href="${PRIVACY_NOTICE_URL}"]`);
    const text = safetyFooter.textContent.replace(/\s+/g, " ").trim();
    if (!safetyLink || !privacyLink || !text.includes("Scams and Risks guidance") || !text.includes("may access and analyse your submission")) {
      issues.push(PROTECTED_SECTIONS[2].label);
    }
  }

  return issues;
}

export function restoreProtectedContent(html, canonicalHtml) {
  const doc = parseEmail(html);
  const canonical = parseEmail(canonicalHtml);
  const shellBody = doc.querySelector(".email-shell > tbody");
  if (!shellBody) return canonicalHtml;

  PROTECTED_SECTIONS.forEach((section) => {
    const selector = `[data-protected-section="${section.id}"]`;
    const source = canonical.querySelector(selector);
    if (!source) return;
    const replacement = doc.importNode(source, true);
    const current = doc.querySelector(selector);
    if (current) {
      current.replaceWith(replacement);
      return;
    }

    if (section.id === "brand-header") {
      shellBody.children[0]?.after(replacement);
      return;
    }
    if (section.id === "institution-footer") {
      const safety = doc.querySelector('[data-protected-section="safety-footer"]');
      if (safety) shellBody.insertBefore(replacement, safety);
      else shellBody.appendChild(replacement);
      return;
    }
    shellBody.appendChild(replacement);
  });

  return `<!doctype html>\n${doc.documentElement.outerHTML}`;
}

export function serializeEmailDocument(sourceDocument) {
  const doc = parseEmail(`<!doctype html>${sourceDocument.documentElement.outerHTML}`);
  normaliseContactNamesInDocument(doc);
  removeEditorMetadata(doc);
  ensureHiddenCreditInDocument(doc);
  return `<!doctype html>\n${doc.documentElement.outerHTML}`;
}

export function cleanEmailHtml(html) {
  const doc = parseEmail(html);
  normaliseContactNamesInDocument(doc);
  removeDeletedContentBlocks(doc);
  removeDisabledModules(doc);
  removeEditorMetadata(doc);
  removeExportMetadata(doc);
  removeUnsafeContent(doc);
  ensureHiddenCreditInDocument(doc);
  return `<!doctype html>\n${doc.documentElement.outerHTML}`;
}

export function getEmailModules(html) {
  const doc = parseEmail(html);
  return Object.fromEntries(EMAIL_MODULES.map((module) => {
    const nodes = [...doc.querySelectorAll(`[data-email-module="${module.id}"]`)];
    const enabled = nodes.length > 0 && nodes.some((node) => node.dataset.moduleEnabled !== "false" && node.dataset.contentBlockDeleted !== "true" && !node.hasAttribute("hidden"));
    return [module.id, enabled];
  }));
}

export function getContentBlocks(html) {
  const doc = parseEmail(html);
  return [...doc.querySelectorAll("[data-content-block]")]
    .filter((element) => element.dataset.contentBlockDeleted !== "true")
    .map((element) => ({
      id: element.dataset.contentBlock,
      type: element.dataset.contentBlockType || "content",
      label: element.dataset.contentBlockLabel || "Content block",
      core: element.dataset.contentBlockCore === "true",
    }));
}

export function addContentBlock(html, type, blockId, placement = {}) {
  const doc = parseEmail(html);
  const definition = CONTENT_BLOCK_TYPES.find((item) => item.id === type);
  const builder = CONTENT_BLOCK_BUILDERS[type];
  const destination = doc.querySelector(".email-body-content");
  if (!definition || !builder || !destination) return html;

  const safeId = String(blockId || `block-${Date.now()}`).replace(/[^a-z0-9_-]/gi, "-");
  const template = doc.createElement("template");
  template.innerHTML = builder({ id: safeId, label: definition.label });
  const block = template.content.firstElementChild;
  const beforeBlock = placement.beforeBlockId
    ? destination.querySelector(`[data-content-block="${CSS.escape(placement.beforeBlockId)}"]`)
    : null;
  if (beforeBlock) {
    destination.insertBefore(block, beforeBlock);
    return `<!doctype html>\n${doc.documentElement.outerHTML}`;
  }
  if (placement.atEnd) {
    destination.appendChild(block);
    return `<!doctype html>\n${doc.documentElement.outerHTML}`;
  }
  const signoff = destination.querySelector('.signoff[data-content-block]');
  destination.insertBefore(block, signoff || null);
  return `<!doctype html>\n${doc.documentElement.outerHTML}`;
}

export function repositionContentBlock(html, blockId, beforeBlockId = null) {
  const doc = parseEmail(html);
  const destination = doc.querySelector(".email-body-content");
  const block = destination?.querySelector(`[data-content-block="${CSS.escape(blockId)}"]`);
  if (!destination || !block) return html;

  if (beforeBlockId) {
    const beforeBlock = destination.querySelector(`[data-content-block="${CSS.escape(beforeBlockId)}"]`);
    if (!beforeBlock || beforeBlock === block) return html;
    destination.insertBefore(block, beforeBlock);
  } else {
    destination.appendChild(block);
  }

  return `<!doctype html>\n${doc.documentElement.outerHTML}`;
}

export function removeContentBlock(html, blockId) {
  const doc = parseEmail(html);
  const block = doc.querySelector(`[data-content-block="${CSS.escape(blockId)}"]`);
  if (!block) return html;
  block.dataset.contentBlockDeleted = "true";
  block.setAttribute("hidden", "");
  block.style.setProperty("display", "none", "important");
  const style = block.getAttribute("style") || "";
  if (!/mso-hide\s*:/i.test(style)) block.setAttribute("style", `${style} mso-hide:all;`.trim());
  return `<!doctype html>\n${doc.documentElement.outerHTML}`;
}

export function moveContentBlock(html, blockId, direction) {
  const doc = parseEmail(html);
  const block = doc.querySelector(`[data-content-block="${CSS.escape(blockId)}"]`);
  const parent = block?.parentElement;
  if (!block || !parent) return html;
  const siblings = [...parent.children].filter((element) => element.hasAttribute("data-content-block") && element.dataset.contentBlockDeleted !== "true");
  const index = siblings.indexOf(block);
  if (direction === "up" && index > 0) parent.insertBefore(block, siblings[index - 1]);
  if (direction === "down" && index >= 0 && index < siblings.length - 1) parent.insertBefore(siblings[index + 1], block);
  return `<!doctype html>\n${doc.documentElement.outerHTML}`;
}

export function updateEmailModules(html, changes) {
  const doc = parseEmail(html);
  EMAIL_MODULES.forEach((module) => {
    if (Object.hasOwn(changes, module.id)) setModuleEnabled(doc, module.id, Boolean(changes[module.id]));
  });
  return `<!doctype html>\n${doc.documentElement.outerHTML}`;
}

export function applyEmailPreset(html, preset) {
  const doc = parseEmail(html);
  const content = preset.content || {};

  doc.title = preset.subject || doc.title;
  setText(doc, ".preheader", content.summary);
  setText(doc, ".category", content.category);
  setText(doc, ".headline", content.headline);
  setText(doc, ".summary", content.summary);
  setText(doc, ".intro-primary", content.introPrimary);
  setText(doc, ".intro-secondary", content.introSecondary);
  setText(doc, ".key-points-heading", content.keyPointsHeading);
  setText(doc, ".button-link", content.buttonLabel);
  setText(doc, ".follow-up-copy", content.followUp);

  if (Array.isArray(content.facts)) {
    const labels = doc.querySelectorAll(".fact-label");
    const values = doc.querySelectorAll(".fact-value");
    content.facts.forEach(([label, value], index) => {
      if (labels[index]) labels[index].textContent = label;
      if (values[index]) values[index].textContent = value;
    });
  }

  if (Array.isArray(content.keyPoints)) {
    const titles = doc.querySelectorAll(".key-point-title");
    const details = doc.querySelectorAll(".key-point-detail");
    content.keyPoints.forEach(([title, detail], index) => {
      if (titles[index]) titles[index].textContent = title;
      if (details[index]) details[index].textContent = detail;
    });
  }

  EMAIL_MODULES.forEach((module) => {
    setModuleEnabled(doc, module.id, preset.modules?.[module.id] !== false);
  });

  return `<!doctype html>\n${doc.documentElement.outerHTML}`;
}

export function getEmailMetadata(html) {
  const doc = parseEmail(html);
  const cta = doc.querySelector(".button-link");
  const email1 = doc.querySelector('[data-contact-index="1"]') || doc.querySelectorAll('a[href^="mailto:"]')[0];
  const email2 = doc.querySelector('[data-contact-index="2"]') || doc.querySelectorAll('a[href^="mailto:"]')[1];
  return {
    ctaUrl: cta?.getAttribute("href") || "",
    contactEmail1: (email1?.getAttribute("href") || "").replace(/^mailto:/i, "") || email1?.textContent?.trim() || "",
    contactEmail2: (email2?.getAttribute("href") || "").replace(/^mailto:/i, "") || email2?.textContent?.trim() || "",
  };
}

export function updateEmailMetadata(html, changes) {
  const doc = parseEmail(html);
  if (Object.hasOwn(changes, "ctaUrl")) {
    doc.querySelector(".button-link")?.setAttribute("href", changes.ctaUrl.trim());
  }
  [1, 2].forEach((index) => {
    const key = `contactEmail${index}`;
    if (!Object.hasOwn(changes, key)) return;
    const email = doc.querySelector(`[data-contact-index="${index}"]`) || doc.querySelectorAll('a[href^="mailto:"]')[index - 1];
    if (!email) return;
    const value = changes[key].trim();
    email.setAttribute("href", `mailto:${value}`);
    email.textContent = value;
    updateContactName(doc, email, index, value);
  });
  return `<!doctype html>\n${doc.documentElement.outerHTML}`;
}
